
FROM ubuntu:18.04

SHELL ["/bin/bash", "-c"]

RUN apt-get update; apt install -y virtualenv; apt-get install -y net-tools; apt-get install -y nano; apt-get install -y python; apt-get install -y python-pip; pip install awscli --upgrade --user; mkdir /root/ftp-server

WORKDIR /root/ftp-server

COPY . .

RUN virtualenv --distribute venv
RUN pip install -r requirements.txt


CMD ["python", "/root/ftp-server/main1.py"]
